### ISSUE TITLE
Add workflow_dispatch for Release Re-runs

### ISSUE THREAD

**Issue by dhyansraj** [dhyansraj/mcp-mesh#1]
## Problem/Request
Currently, when a GitHub release workflow fails (like we experienced with PyPI version conflicts), the only option is to delete and recreate the entire GitHub release. This is inefficient and loses the release history/timestamps.

## Current Behavior
- Create GitHub release → triggers workflow → fails
- Must delete release, fix code, recreate release
- Loses original release timestamp and history
- Cumbersome for iterative fixes

## Desired Behavior
- Create GitHub release → triggers workflow → fails
- Fix code, push changes
- Manually re-run workflow with same version
- No need to recreate GitHub release

## Acceptance Criteria
- [ ] Add `workflow_dispatch` trigger to release.yml
- [ ] Include version input parameter (e.g., "v0.1.1")
- [ ] Include environment input (production/test) for different deployment targets
- [ ] Test workflow can be manually triggered from GitHub Actions UI
- [ ] Workflow correctly uses provided version instead of inferring from tag
- [ ] Documentation updated with re-run instructions

## Implementation Notes
Add to `.github/workflows/release.yml`:
```yaml
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g., v0.1.1)"
        required: true
        default: "v0.1.1"
      environment:
        description: "Environment"
        type: choice
        options: [production, test]
        default: test
```

## Related Issues
This addresses the pain point we experienced during v0.1.1 release where we had to recreate the release multiple times.
