### ISSUE TITLE
Sequential Pipeline: Docker Images After PyPI/CLI Publishing

### ISSUE THREAD

**Issue by dhyansraj** [dhyansraj/mcp-mesh#2]
## Problem/Request
Currently, Docker images, PyPI packages, and CLI binaries are built in parallel from source code. This creates inconsistency where Docker images may contain different code than the published packages, and Docker builds can succeed even if PyPI publishing fails.

## Current Behavior
```yaml
# All run in parallel - race conditions possible
build-binaries: [builds from source]
build-docker: [builds from source] 
publish-python: [publishes to PyPI]
```

Problems:
- Docker might finish before PyPI, causing inconsistent artifacts
- Docker images build from source while users get PyPI packages
- Different dependency resolution between source builds and package installs
- No validation that published packages actually work

## Desired Behavior
```yaml
# Sequential with proper dependencies
publish-python: [publishes to PyPI]
build-binaries: [publishes CLI to GitHub releases]
  ↓
build-docker: 
  needs: [publish-python, build-binaries]
  # Uses: pip install mcp-mesh==0.1.1
  # Uses: curl -L github.com/releases/meshctl
```

## Acceptance Criteria
- [ ] Docker build jobs depend on publish-python and build-binaries completion
- [ ] Docker images install from published PyPI packages, not source
- [ ] Docker images download CLI binaries from GitHub releases, not build from source
- [ ] Update Dockerfiles to use ARG VERSION for package installation
- [ ] Docker builds fail if PyPI/GitHub releases fail (proper dependency chain)
- [ ] Verify Docker images use exact same artifacts that users get
- [ ] Update documentation explaining the new pipeline flow

## Implementation Notes

**Workflow Changes:**
```yaml
build-docker:
  needs: [publish-python, build-binaries]
  steps:
    - name: Build Registry image
      run: |
        docker build -f Dockerfile.registry \
          --build-arg VERSION=0.1.1 \
          --build-arg INSTALL_METHOD="pip install mcp-mesh==0.1.1" \
          .
```

**Dockerfile Changes:**
```dockerfile
# Before: COPY src/ && go build
# After: 
ARG VERSION
RUN curl -L github.com/dhyansraj/mcp-mesh/releases/download/v${VERSION}/meshctl...
RUN pip install mcp-mesh==${VERSION}
```

**Benefits:**
- Consistency: Docker images use exact same artifacts users get
- Real Testing: If PyPI package is broken, Docker build fails
- Speed: No source compilation in Docker (faster builds)
- Reliability: Docker can't succeed if PyPI/releases failed

**Trade-offs:**
- Slower total pipeline (sequential vs parallel)
- More complex if PyPI/releases fail

## Related Issues
This builds on issue #001 (workflow_dispatch) to create a more robust release pipeline.
