### ISSUE TITLE
Pre-release Testing Workflow

### ISSUE THREAD

**Issue by dhyansraj** [dhyansraj/mcp-mesh#3]
## Problem/Request
Currently, there's no safe way to test the release pipeline without publishing to production PyPI and Docker Hub. This led to version conflicts (0.2.0 test versions) that prevented proper v0.1.1 release. We need a pre-release testing workflow.

## Current Behavior
- Create release → immediately publishes to production PyPI/Docker Hub
- Any pipeline failures require recreating releases
- Test versions pollute production package repositories
- No way to validate release process before going live

## Desired Behavior
Two-stage release process:
1. **Pre-release**: Test everything with limited scope
2. **Full release**: Promote to production after validation

## Acceptance Criteria
- [ ] Detect pre-release vs full release from GitHub release settings
- [ ] Pre-release stage publishes to test repositories:
  - Test PyPI instead of production PyPI
  - Docker images with pre-release tags (e.g., `0.1.1-rc1`)
  - Limited distribution for testing
- [ ] Full release stage publishes to production:
  - Production PyPI
  - Docker images with `latest` and version tags
  - Full distribution
- [ ] Clear documentation on pre-release workflow
- [ ] Validation checklist for promoting pre-release to full release

## Implementation Notes

**GitHub Release Workflow:**
1. **Create Pre-release** ✅
   ```
   ☑️ Set as pre-release
   ☑️ Set as draft (optional)
   Title: v0.1.1-rc1
   ```

2. **Test Everything** 🧪
   - Workflow runs in "test mode"
   - Check Test PyPI installation
   - Verify Docker builds
   - Test installation scripts

3. **Publish Final Release** 🚀
   ```
   ☐ Set as pre-release  
   ☐ Set as draft
   Title: v0.1.1
   ```

**Workflow Changes:**
```yaml
# Stage 1: Pre-release (draft or pre-release checked)
publish-python-test:
  if: github.event.release.prerelease == true
  # Deploy to Test PyPI
  # Upload with pre-release tags

# Stage 2: Full release  
publish-python-prod:
  if: github.event.release.prerelease == false
  # Deploy to production PyPI
  # Full Docker tags (latest + version)
```

**Benefits:**
- Safe testing of release pipeline
- No pollution of production repositories
- Validation before public release
- Industry standard practice

## Related Issues
Complements #001 (workflow_dispatch) and #002 (sequential pipeline) for robust release management.
